# Generated by Django 3.1.6 on 2021-03-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('originalName', models.TextField(blank=True)),
                ('birth', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('ISBN', models.CharField(max_length=13)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(blank=True, to='books.Author')),
            ],
            options={
                'verbose_name': '책',
                'verbose_name_plural': '책',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': '국적',
                'verbose_name_plural': '국적',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': '장르',
                'verbose_name_plural': '장르',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': '출판사',
                'verbose_name_plural': '출판사',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': '시리즈',
                'verbose_name_plural': '시리즈',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('book', models.ManyToManyField(blank=True, to='books.Book')),
            ],
            options={
                'verbose_name': '테마',
                'verbose_name_plural': '테마',
            },
        ),
        migrations.CreateModel(
            name='GenreSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parentGenre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.genre')),
            ],
            options={
                'verbose_name': '하위장르',
                'verbose_name_plural': '하위장르',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='books.GenreSub'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(blank=True, to='books.Series'),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.country'),
        ),
    ]
