# Generated by Django 3.1.6 on 2021-03-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('originalName', models.TextField(blank=True)),
                ('birth', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('publish_date', models.DateField(blank=True)),
                ('ISBN', models.CharField(max_length=13)),
                ('page', models.IntegerField(blank=True)),
                ('author', models.ManyToManyField(blank=True, to='books.Author')),
                ('genre', models.ManyToManyField(blank=True, to='books.Genre')),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='books.publisher')),
            ],
            options={
                'verbose_name': '책',
                'verbose_name_plural': '책',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='books.country'),
        ),
    ]
