# Generated by Django 3.1.6 on 2021-03-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Pricetag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discountedPrice', models.IntegerField(blank=True, null=True)),
                ('outOfStock', models.BooleanField(default=False)),
                ('isDigital', models.BooleanField()),
                ('isRental', models.BooleanField(default=False)),
                ('rentalPeriod', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.company')),
            ],
        ),
    ]
