# Generated by Django 3.1.6 on 2021-03-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_genresub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '작가', 'verbose_name_plural': '작가'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '국적', 'verbose_name_plural': '국적'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': '장르', 'verbose_name_plural': '장르'},
        ),
        migrations.AlterModelOptions(
            name='genresub',
            options={'verbose_name': '하위장르', 'verbose_name_plural': '하위장르'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '출판사', 'verbose_name_plural': '출판사'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': '시리즈', 'verbose_name_plural': '시리즈'},
        ),
    ]
